/** fullsize.js
 * JavaScipt handling for the fullsize image clickthrough pages 
 */

//import vars and functions
import {
    prods,
    sourceURL,
    fallbackImage,
    fileext,
    generateShareURL,
    shareToast,
    utcToLocalDate,
    disableNext,
    formatDate,
    getStoredOrURLParam
} from './utils.js';

import { initializeSidebar } from './sidebar.js';

let datepicker;
let activeProds = new Set(prods); 

// set image location from activeDate 
const getImageName = (yyyy, mm, dd, product, ext) =>
    `${yyyy}${mm}${dd}_${product}${ext}`;
const getImageURL = (base, year, month, name) =>
    `${base}${year}${month}/${name}`;

// wait for DOM to build
document.addEventListener('DOMContentLoaded', () => {
    // initialize controlsContainer (center) buttons 
    const prevButton = document.getElementById('prevButton');
    const nextButton = document.getElementById('nextButton');
    const backToGridButton = document.getElementById('backToGridButton');

    // imageContainer: div container for all fullsize images 
    const imageContainer = document.getElementById('fullsizeImageContainer');

    // parse date from URL params generated by the grid 
    const now = new Date();
    const year = getStoredOrURLParam('year', String(now.getUTCFullYear()));
    const month = getStoredOrURLParam('month', String(now.getUTCMonth() + 1).padStart(2, '0'));
    const day = getStoredOrURLParam('day', String(now.getUTCDate()).padStart(2, '0'));
    const thumb = getStoredOrURLParam('thumb', 'default-thumb');
    // note that months start at 0 in js
    let activeDate = new Date(Date.UTC(parseInt(year), parseInt(month) - 1, parseInt(day)));

    // initialize calendar 
    datepicker = new AirDatepicker('#fullsizecal', {
        locale: {
            days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
            daysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
            daysMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            today: 'Today',
            clear: 'Clear',
            dateFormat: 'yyyy-MM-dd',
            timeFormat: 'hh:mm aa',
            firstDay: 0
        },
        autoClose: true,
        defaultDate: utcToLocalDate(activeDate),
        // update the calendar and the images in imageContainer upon date selection 
        onSelect({ date }) {
            if (date) {
                activeDate = new Date(Date.UTC(
                    date.getFullYear(),
                    date.getMonth(),
                    date.getDate()
                ));
                updateFullSizeImages();
                // update sessionStorage with selected date from cal 
                const { yyyy, mm, dd } = formatDate(activeDate);
                sessionStorage.setItem('year', yyyy);
                sessionStorage.setItem('month', mm);
                sessionStorage.setItem('day', dd);
            }
        }
    });

    // set initial calendar date to activeDate 
    document.querySelector('#fullsizecal').value = activeDate.toISOString().split('T')[0];
    datepicker.selectDate(utcToLocalDate(activeDate), true);

    // define function: populate images in imageContainer
    function updateFullSizeImages() {
        // get date as string for image URLs
        const { yyyy, mm, dd } = formatDate(activeDate);

        // check if activeDate = today and disable the Next button
        disableNext(nextButton, activeDate);

        // initialize the image container 
        imageContainer.innerHTML = '';
        
        // Check if no products are active and show message if needed
        if (activeProds.size === 0) {
            const messageDiv = document.createElement('div');
            messageDiv.id = 'no-products-message';
            messageDiv.textContent = 'Select a product from the menu';
            imageContainer.appendChild(messageDiv);
            return;
        }
        
        // load each product image
        prods.forEach(product => {
            // construct image name and URL
            if (!activeProds.has(product)) return;
            const imageName = getImageName(yyyy, mm, dd, product, fileext);
            const imageURL = getImageURL(sourceURL, yyyy, mm, imageName);
            // console.log('Looking for image URL: ', imageURL)
    
            // Wrapper div for each image (enables scroll to anchor ID)
            const wrapper = document.createElement('div');
            wrapper.className = 'fullsize-image-wrapper';
            wrapper.id = product; // enables #anchor scrolling
    
            // Image element (sits within the wrapper)
            const img = document.createElement('img');
            img.alt = `${product} image`;
            img.className = 'fullsizeImage';
    
            // Link around image (enables hyperlink to image on click)
            const link = document.createElement('a');
            link.href = imageURL; // change image link destination here
            link.target = '_blank';
            link.appendChild(img);
            
            // add children to wrapper
            wrapper.appendChild(link);
            imageContainer.appendChild(wrapper);
    
            // Test if image exists before showing it
            const imagePreloader = new Image();
            imagePreloader.onload = () => {
                img.src = imageURL;
            };
            imagePreloader.onerror = () => {
                img.src = fallbackImage;
                link.href = fallbackImage;
            };
            imagePreloader.src = imageURL;
        });
    }

    // define function: change date when prev/next buttons are clicked
    function changeDate(days) {
        activeDate.setUTCDate(activeDate.getUTCDate() + days);
        const { yyyy, mm, dd } = formatDate(activeDate);
        sessionStorage.setItem('year', yyyy);
        sessionStorage.setItem('month', mm);
        sessionStorage.setItem('day', dd);
        disableNext(nextButton, activeDate);
        document.querySelector('#fullsizecal').value = activeDate.toISOString().split('T')[0];
        datepicker.selectDate(utcToLocalDate(activeDate), true);
        updateFullSizeImages();
    }

    // listen for prev/next/grid button clicks
    prevButton.addEventListener('click', () => changeDate(-1));
    nextButton.addEventListener('click', () => changeDate(1));
    backToGridButton.addEventListener('click', () => {
        const { yyyy, mm, dd } = formatDate(activeDate);
        window.location.href = `index.html?year=${yyyy}&month=${mm}&day=${dd}&thumb=${encodeURIComponent(thumb)}`;
    });

    // copy link button
    document.getElementById('copyLinkButton').addEventListener('click', () => {
        const thumb = sessionStorage.getItem('thumb') || 'default-thumb';
        const shareURL = generateShareURL(activeDate, thumb);
    
        navigator.clipboard.writeText(shareURL)
            .then(() => shareToast('✅ Link copied to clipboard'))
            .catch(err => console.error('Failed to copy link: ', err));
    });

    // initialize sidebar (sidebar.js)
    initializeSidebar(activeProds, updateFullSizeImages); 
    
    // Initial call to show images or "no products" message (main image loader function)
    updateFullSizeImages();
});

// define function: scroll to anchor after image loads (for slow internet connections)
function scrollToLoadedImage(anchorId, retries = 20) {
    if (retries <= 0) return;
    const el = document.getElementById(anchorId);
    if (!el) {
        // Element doesn't exist yet, try again next frame
        requestAnimationFrame(() => scrollToLoadedElement(anchorId, retries - 1));
        return;
    }
    // Find all images inside this element
    const images = el.querySelectorAll('img');
    // If no images or all images are loaded/have error
    if (images.length === 0 || Array.from(images).every(img => img.complete)) {
        // All content is ready, scroll now
        el.scrollIntoView({ behavior: 'smooth', block: 'start' });
        return;
    }
    // At least one image is still loading, check again after a delay
    setTimeout(() => scrollToLoadedImage(anchorId, retries - 1), 100);
}

// jump to image anchor 
const anchor = window.location.hash?.substring(1);
if (anchor) {
    scrollToLoadedImage(anchor);
}